In [36]:
import pandas as pd
import numpy as np

In [37]:
df= pd.read_csv('D:/Sets of excel and bi/customer_support_tickets.csv')

In [38]:
df.shape

(8469, 17)

In [39]:
df.dtypes

Ticket ID                         int64
Customer Name                    object
Customer Email                   object
Customer Age                      int64
Customer Gender                  object
Product Purchased                object
Date of Purchase                 object
Ticket Type                      object
Ticket Subject                   object
Ticket Description               object
Ticket Status                    object
Resolution                       object
Ticket Priority                  object
Ticket Channel                   object
First Response Time              object
Time to Resolution               object
Customer Satisfaction Rating    float64
dtype: object

In [40]:
df.describe()

         Ticket ID  Customer Age  Customer Satisfaction Rating
count  8469.000000   8469.000000                   2769.000000
mean   4235.000000     44.026804                      2.991333
std    2444.934048     15.296112                      1.407016
min       1.000000     18.000000                      1.000000
25%    2118.000000     31.000000                      2.000000
50%    4235.000000     44.000000                      3.000000
75%    6352.000000     57.000000                      4.000000
max    8469.000000     70.000000                      5.000000

In [41]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [42]:
#fixing datatypes
df['Date of Purchase'] = pd.to_datetime(df['Date of Purchase'], errors='coerce')
#for both date and time
cols = ['First Response Time', 'Time to Resolution']
df[cols] = df[cols].apply(pd.to_datetime, errors='coerce')
#category
cols = ['Customer Gender','Ticket Type','Ticket Status',
    'Ticket Priority','Ticket Channel','Product Purchased']
df[cols] = df[cols].astype('category')

In [43]:
#convert every null value to NaN
df.replace(['NULL', 'None', 'N/A'], np.nan, inplace=True)

In [44]:
df.isnull().sum() / len(df) * 100

Ticket ID                        0.000000
Customer Name                    0.000000
Customer Email                   0.000000
Customer Age                     0.000000
Customer Gender                  0.000000
Product Purchased                0.000000
Date of Purchase                 0.000000
Ticket Type                      0.000000
Ticket Subject                   0.000000
Ticket Description               0.000000
Ticket Status                    0.000000
Resolution                      67.304286
Ticket Priority                  0.000000
Ticket Channel                   0.000000
First Response Time             33.286102
Time to Resolution              67.304286
Customer Satisfaction Rating    67.304286
dtype: float64

In [45]:
#fill Null values
df['Customer Satisfaction Rating'] = df['Customer Satisfaction Rating'].fillna(0)
df['Time to Resolution'] = df['Time to Resolution'].fillna(0)
df['First Response Time'] = df['First Response Time'].fillna(0)
df['Resolution'] = df['Resolution'].fillna('Not Resolved')

In [46]:
df.isnull().sum() / len(df) * 100

Ticket ID                       0.0
Customer Name                   0.0
Customer Email                  0.0
Customer Age                    0.0
Customer Gender                 0.0
Product Purchased               0.0
Date of Purchase                0.0
Ticket Type                     0.0
Ticket Subject                  0.0
Ticket Description              0.0
Ticket Status                   0.0
Resolution                      0.0
Ticket Priority                 0.0
Ticket Channel                  0.0
First Response Time             0.0
Time to Resolution              0.0
Customer Satisfaction Rating    0.0
dtype: float64

In [47]:
df.duplicated().sum()

0

In [48]:
df.nunique()

Ticket ID                       8469
Customer Name                   8028
Customer Email                  8320
Customer Age                      53
Customer Gender                    3
Product Purchased                 42
Date of Purchase                 730
Ticket Type                        5
Ticket Subject                    16
Ticket Description              8077
Ticket Status                      3
Resolution                      2770
Ticket Priority                    4
Ticket Channel                     4
First Response Time             5471
Time to Resolution              2729
Customer Satisfaction Rating       6
dtype: int64

In [49]:
#check in case of difference(male,MALE)
df['Customer Gender'].value_counts()

Customer Gender
Male      2896
Female    2887
Other     2686
Name: count, dtype: int64

In [50]:
df['Customer Gender'] = df['Customer Gender'].str.strip().str.lower()

In [51]:
df['Customer Gender'].value_counts()

Customer Gender
male      2896
female    2887
other     2686
Name: count, dtype: int64

In [52]:
#checking rating does not contain outlier
(~df['Customer Satisfaction Rating'].between(0, 5)).sum()

0

In [53]:
# Fix spelling variations with a mapping
category_map = {
    'tech support': 'Technical Support',
    'Tech Support': 'Technical Support',
    'TECH SUPPORT': 'Technical Support',
    'tech-support': 'Technical Support'
}
df['Product Purchased'] = df['Product Purchased'].replace(category_map)

In [54]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,Not Resolved,Critical,Social media,2023-06-01 12:15:36,0,0.0
1,2,Jessica Rios,clarkeashley@example.com,42,female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,Not Resolved,Critical,Chat,2023-06-01 16:45:38,0,0.0
2,3,Christopher Robbins,gonzalestracy@example.com,48,other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0